export const DefaultLanguages = [
	{
		category: "Most used",
		locales: [
			{code: "cmn", name: "Mandarin Chinese"},
			{code: "es", name: "Spanish"},
			{code: "en", name: "English"},
			{code: "hi", name: "Hindi"},
			{code: "bn", name: "Bengali"},
			{code: "pt", name: "Portuguese"},
			{code: "ru", name: "Russian"},
			{code: "ja", name: "Japanese"},
			{code: "pa", name: "Punjabi"},
			{code: "yue", name: "Yue Chinese"},
			{code: "vi", name: "Vietnamese"},
			{code: "tr", name: "Turkish"},
			{code: "ko", name: "Korean"},
			{code: "fr", name: "French"},
			{code: "de", name: "German"},
			{code: "it", name: "Italian"}
		]
	},
	{
		category: "Rest",
		locales: [
			{code: "zh-CN", name: "Chinese (China)"},
			{code: "zh-TW", name: "Chinese (Traditional, Taiwan)"},
			{code: "af", name: "Afrikaans"},
			{code: "af-NA", name: "Afrikaans (Namibia)"},
			{code: "af-ZA", name: "Afrikaans (South Africa)"},
			{code: "agq", name: "Aghem"},
			{code: "agq-CM", name: "Aghem (Cameroon)"},
			{code: "ak", name: "Akan"},
			{code: "ak-GH", name: "Akan (Ghana)"},
			{code: "am", name: "Amharic"},
			{code: "am-ET", name: "Amharic (Ethiopia)"},
			{code: "ar", name: "Arabic"},
			{code: "ar-001", name: "Arabic (World)"},
			{code: "ar-AE", name: "Arabic (United Arab Emirates)"},
			{code: "ar-BH", name: "Arabic (Bahrain)"},
			{code: "ar-DJ", name: "Arabic (Djibouti)"},
			{code: "ar-DZ", name: "Arabic (Algeria)"},
			{code: "ar-EG", name: "Arabic (Egypt)"},
			{code: "ar-EH", name: "Arabic (Western Sahara)"},
			{code: "ar-ER", name: "Arabic (Eritrea)"},
			{code: "ar-IL", name: "Arabic (Israel)"},
			{code: "ar-IQ", name: "Arabic (Iraq)"},
			{code: "ar-JO", name: "Arabic (Jordan)"},
			{code: "ar-KM", name: "Arabic (Comoros)"},
			{code: "ar-KW", name: "Arabic (Kuwait)"},
			{code: "ar-LB", name: "Arabic (Lebanon)"},
			{code: "ar-LY", name: "Arabic (Libya)"},
			{code: "ar-MA", name: "Arabic (Morocco)"},
			{code: "ar-MR", name: "Arabic (Mauritania)"},
			{code: "ar-OM", name: "Arabic (Oman)"},
			{code: "ar-PS", name: "Arabic (Palestinian Territories)"},
			{code: "ar-QA", name: "Arabic (Qatar)"},
			{code: "ar-SA", name: "Arabic (Saudi Arabia)"},
			{code: "ar-SD", name: "Arabic (Sudan)"},
			{code: "ar-SO", name: "Arabic (Somalia)"},
			{code: "ar-SS", name: "Arabic (South Sudan)"},
			{code: "ar-SY", name: "Arabic (Syria)"},
			{code: "ar-TD", name: "Arabic (Chad)"},
			{code: "ar-TN", name: "Arabic (Tunisia)"},
			{code: "ar-YE", name: "Arabic (Yemen)"},
			{code: "as", name: "Assamese"},
			{code: "as-IN", name: "Assamese (India)"},
			{code: "asa", name: "Asu"},
			{code: "asa-TZ", name: "Asu (Tanzania)"},
			{code: "ast", name: "Asturian"},
			{code: "ast-ES", name: "Asturian (Spain)"},
			{code: "az", name: "Azerbaijani"},
			{code: "az-Cyrl", name: "Azerbaijani (Cyrillic)"},
			{code: "az-Cyrl-AZ", name: "Azerbaijani (Cyrillic, Azerbaijan)"},
			{code: "az-Latn", name: "Azerbaijani (Latin)"},
			{code: "az-Latn-AZ", name: "Azerbaijani (Latin, Azerbaijan)"},
			{code: "bas", name: "Basaa"},
			{code: "bas-CM", name: "Basaa (Cameroon)"},
			{code: "be", name: "Belarusian"},
			{code: "be-BY", name: "Belarusian (Belarus)"},
			{code: "bem", name: "Bemba"},
			{code: "bem-ZM", name: "Bemba (Zambia)"},
			{code: "bez", name: "Bena"},
			{code: "bez-TZ", name: "Bena (Tanzania)"},
			{code: "bg", name: "Bulgarian"},
			{code: "bg-BG", name: "Bulgarian (Bulgaria)"},
			{code: "bm", name: "Bambara"},
			{code: "bm-ML", name: "Bambara (Mali)"},
			{code: "bn", name: "Bangla"},
			{code: "bn-BD", name: "Bangla (Bangladesh)"},
			{code: "bn-IN", name: "Bangla (India)"},
			{code: "bo", name: "Tibetan"},
			{code: "bo-CN", name: "Tibetan (China)"},
			{code: "bo-IN", name: "Tibetan (India)"},
			{code: "br", name: "Breton"},
			{code: "br-FR", name: "Breton (France)"},
			{code: "brx", name: "Bodo"},
			{code: "brx-IN", name: "Bodo (India)"},
			{code: "bs", name: "Bosnian"},
			{code: "bs-Cyrl", name: "Bosnian (Cyrillic)"},
			{code: "bs-Cyrl-BA", name: "Bosnian (Cyrillic, Bosnia & Herzegovina)"},
			{code: "bs-Latn", name: "Bosnian (Latin)"},
			{code: "bs-Latn-BA", name: "Bosnian (Latin, Bosnia & Herzegovina)"},
			{code: "ca", name: "Catalan"},
			{code: "ca-AD", name: "Catalan (Andorra)"},
			{code: "ca-ES", name: "Catalan (Spain)"},
			{code: "ca-FR", name: "Catalan (France)"},
			{code: "ca-IT", name: "Catalan (Italy)"},
			{code: "ccp", name: "Chakma"},
			{code: "ccp-BD", name: "Chakma (Bangladesh)"},
			{code: "ccp-IN", name: "Chakma (India)"},
			{code: "ce", name: "Chechen"},
			{code: "ce-RU", name: "Chechen (Russia)"},
			{code: "cgg", name: "Chiga"},
			{code: "cgg-UG", name: "Chiga (Uganda)"},
			{code: "chr", name: "Cherokee"},
			{code: "chr-US", name: "Cherokee (United States)"},
			{code: "ckb", name: "Central Kurdish"},
			{code: "ckb-IQ", name: "Central Kurdish (Iraq)"},
			{code: "ckb-IR", name: "Central Kurdish (Iran)"},
			{code: "cs", name: "Czech"},
			{code: "cs-CZ", name: "Czech (Czechia)"},
			{code: "cy", name: "Welsh"},
			{code: "cy-GB", name: "Welsh (United Kingdom)"},
			{code: "da", name: "Danish"},
			{code: "da-DK", name: "Danish (Denmark)"},
			{code: "da-GL", name: "Danish (Greenland)"},
			{code: "dav", name: "Taita"},
			{code: "dav-KE", name: "Taita (Kenya)"},
			{code: "de", name: "German"},
			{code: "de-AT", name: "German (Austria)"},
			{code: "de-BE", name: "German (Belgium)"},
			{code: "de-CH", name: "German (Switzerland)"},
			{code: "de-DE", name: "German (Germany)"},
			{code: "de-IT", name: "German (Italy)"},
			{code: "de-LI", name: "German (Liechtenstein)"},
			{code: "de-LU", name: "German (Luxembourg)"},
			{code: "dje", name: "Zarma"},
			{code: "dje-NE", name: "Zarma (Niger)"},
			{code: "dsb", name: "Lower Sorbian"},
			{code: "dsb-DE", name: "Lower Sorbian (Germany)"},
			{code: "dua", name: "Duala"},
			{code: "dua-CM", name: "Duala (Cameroon)"},
			{code: "dyo", name: "Jola-Fonyi"},
			{code: "dyo-SN", name: "Jola-Fonyi (Senegal)"},
			{code: "dz", name: "Dzongkha"},
			{code: "dz-BT", name: "Dzongkha (Bhutan)"},
			{code: "ebu", name: "Embu"},
			{code: "ebu-KE", name: "Embu (Kenya)"},
			{code: "ee", name: "Ewe"},
			{code: "ee-GH", name: "Ewe (Ghana)"},
			{code: "ee-TG", name: "Ewe (Togo)"},
			{code: "el", name: "Greek"},
			{code: "el-CY", name: "Greek (Cyprus)"},
			{code: "el-GR", name: "Greek (Greece)"},
			{code: "en", name: "English"},
			{code: "en-001", name: "English (World)"},
			{code: "en-150", name: "English (Europe)"},
			{code: "en-AG", name: "English (Antigua & Barbuda)"},
			{code: "en-AI", name: "English (Anguilla)"},
			{code: "en-AS", name: "English (American Samoa)"},
			{code: "en-AT", name: "English (Austria)"},
			{code: "en-AU", name: "English (Australia)"},
			{code: "en-BB", name: "English (Barbados)"},
			{code: "en-BE", name: "English (Belgium)"},
			{code: "en-BI", name: "English (Burundi)"},
			{code: "en-BM", name: "English (Bermuda)"},
			{code: "en-BS", name: "English (Bahamas)"},
			{code: "en-BW", name: "English (Botswana)"},
			{code: "en-BZ", name: "English (Belize)"},
			{code: "en-CA", name: "English (Canada)"},
			{code: "en-CC", name: "English (Cocos [Keeling] Islands)"},
			{code: "en-CH", name: "English (Switzerland)"},
			{code: "en-CK", name: "English (Cook Islands)"},
			{code: "en-CM", name: "English (Cameroon)"},
			{code: "en-CX", name: "English (Christmas Island)"},
			{code: "en-CY", name: "English (Cyprus)"},
			{code: "en-DE", name: "English (Germany)"},
			{code: "en-DG", name: "English (Diego Garcia)"},
			{code: "en-DK", name: "English (Denmark)"},
			{code: "en-DM", name: "English (Dominica)"},
			{code: "en-ER", name: "English (Eritrea)"},
			{code: "en-FI", name: "English (Finland)"},
			{code: "en-FJ", name: "English (Fiji)"},
			{code: "en-FK", name: "English (Falkland Islands)"},
			{code: "en-FM", name: "English (Micronesia)"},
			{code: "en-GB", name: "English (United Kingdom)"},
			{code: "en-GD", name: "English (Grenada)"},
			{code: "en-GG", name: "English (Guernsey)"},
			{code: "en-GH", name: "English (Ghana)"},
			{code: "en-GI", name: "English (Gibraltar)"},
			{code: "en-GM", name: "English (Gambia)"},
			{code: "en-GU", name: "English (Guam)"},
			{code: "en-GY", name: "English (Guyana)"},
			{code: "en-HK", name: "English (Hong Kong SAR China)"},
			{code: "en-IE", name: "English (Ireland)"},
			{code: "en-IL", name: "English (Israel)"},
			{code: "en-IM", name: "English (Isle of Man)"},
			{code: "en-IN", name: "English (India)"},
			{code: "en-IO", name: "English (British Indian Ocean Territory)"},
			{code: "en-JE", name: "English (Jersey)"},
			{code: "en-JM", name: "English (Jamaica)"},
			{code: "en-KE", name: "English (Kenya)"},
			{code: "en-KI", name: "English (Kiribati)"},
			{code: "en-KN", name: "English (St. Kitts & Nevis)"},
			{code: "en-KY", name: "English (Cayman Islands)"},
			{code: "en-LC", name: "English (St. Lucia)"},
			{code: "en-LR", name: "English (Liberia)"},
			{code: "en-LS", name: "English (Lesotho)"},
			{code: "en-MG", name: "English (Madagascar)"},
			{code: "en-MH", name: "English (Marshall Islands)"},
			{code: "en-MO", name: "English (Macau SAR China)"},
			{code: "en-MP", name: "English (Northern Mariana Islands)"},
			{code: "en-MS", name: "English (Montserrat)"},
			{code: "en-MT", name: "English (Malta)"},
			{code: "en-MU", name: "English (Mauritius)"},
			{code: "en-MW", name: "English (Malawi)"},
			{code: "en-MY", name: "English (Malaysia)"},
			{code: "en-NA", name: "English (Namibia)"},
			{code: "en-NF", name: "English (Norfolk Island)"},
			{code: "en-NG", name: "English (Nigeria)"},
			{code: "en-NL", name: "English (Netherlands)"},
			{code: "en-NR", name: "English (Nauru)"},
			{code: "en-NU", name: "English (Niue)"},
			{code: "en-NZ", name: "English (New Zealand)"},
			{code: "en-PG", name: "English (Papua New Guinea)"},
			{code: "en-PH", name: "English (Philippines)"},
			{code: "en-PK", name: "English (Pakistan)"},
			{code: "en-PN", name: "English (Pitcairn Islands)"},
			{code: "en-PR", name: "English (Puerto Rico)"},
			{code: "en-PW", name: "English (Palau)"},
			{code: "en-RW", name: "English (Rwanda)"},
			{code: "en-SB", name: "English (Solomon Islands)"},
			{code: "en-SC", name: "English (Seychelles)"},
			{code: "en-SD", name: "English (Sudan)"},
			{code: "en-SE", name: "English (Sweden)"},
			{code: "en-SG", name: "English (Singapore)"},
			{code: "en-SH", name: "English (St. Helena)"},
			{code: "en-SI", name: "English (Slovenia)"},
			{code: "en-SL", name: "English (Sierra Leone)"},
			{code: "en-SS", name: "English (South Sudan)"},
			{code: "en-SX", name: "English (Sint Maarten)"},
			{code: "en-SZ", name: "English (Swaziland)"},
			{code: "en-TC", name: "English (Turks & Caicos Islands)"},
			{code: "en-TK", name: "English (Tokelau)"},
			{code: "en-TO", name: "English (Tonga)"},
			{code: "en-TT", name: "English (Trinidad & Tobago)"},
			{code: "en-TV", name: "English (Tuvalu)"},
			{code: "en-TZ", name: "English (Tanzania)"},
			{code: "en-UG", name: "English (Uganda)"},
			{code: "en-UM", name: "English (U.S. Outlying Islands)"},
			{code: "en-US", name: "English (United States)"},
			{code: "en-US-POSIX", name: "English (United States, Computer)"},
			{code: "en-VC", name: "English (St. Vincent & Grenadines)"},
			{code: "en-VG", name: "English (British Virgin Islands)"},
			{code: "en-VI", name: "English (U.S. Virgin Islands)"},
			{code: "en-VU", name: "English (Vanuatu)"},
			{code: "en-WS", name: "English (Samoa)"},
			{code: "en-ZA", name: "English (South Africa)"},
			{code: "en-ZM", name: "English (Zambia)"},
			{code: "en-ZW", name: "English (Zimbabwe)"},
			{code: "eo", name: "Esperanto"},
			{code: "es", name: "Spanish"},
			{code: "es-419", name: "Spanish (Latin America)"},
			{code: "es-AR", name: "Spanish (Argentina)"},
			{code: "es-BO", name: "Spanish (Bolivia)"},
			{code: "es-BR", name: "Spanish (Brazil)"},
			{code: "es-BZ", name: "Spanish (Belize)"},
			{code: "es-CL", name: "Spanish (Chile)"},
			{code: "es-CO", name: "Spanish (Colombia)"},
			{code: "es-CR", name: "Spanish (Costa Rica)"},
			{code: "es-CU", name: "Spanish (Cuba)"},
			{code: "es-DO", name: "Spanish (Dominican Republic)"},
			{code: "es-EA", name: "Spanish (Ceuta & Melilla)"},
			{code: "es-EC", name: "Spanish (Ecuador)"},
			{code: "es-ES", name: "Spanish (Spain)"},
			{code: "es-GQ", name: "Spanish (Equatorial Guinea)"},
			{code: "es-GT", name: "Spanish (Guatemala)"},
			{code: "es-HN", name: "Spanish (Honduras)"},
			{code: "es-IC", name: "Spanish (Canary Islands)"},
			{code: "es-MX", name: "Spanish (Mexico)"},
			{code: "es-NI", name: "Spanish (Nicaragua)"},
			{code: "es-PA", name: "Spanish (Panama)"},
			{code: "es-PE", name: "Spanish (Peru)"},
			{code: "es-PH", name: "Spanish (Philippines)"},
			{code: "es-PR", name: "Spanish (Puerto Rico)"},
			{code: "es-PY", name: "Spanish (Paraguay)"},
			{code: "es-SV", name: "Spanish (El Salvador)"},
			{code: "es-US", name: "Spanish (United States)"},
			{code: "es-UY", name: "Spanish (Uruguay)"},
			{code: "es-VE", name: "Spanish (Venezuela)"},
			{code: "et", name: "Estonian"},
			{code: "et-EE", name: "Estonian (Estonia)"},
			{code: "eu", name: "Basque"},
			{code: "eu-ES", name: "Basque (Spain)"},
			{code: "ewo", name: "Ewondo"},
			{code: "ewo-CM", name: "Ewondo (Cameroon)"},
			{code: "fa", name: "Persian"},
			{code: "fa-AF", name: "Persian (Afghanistan)"},
			{code: "fa-IR", name: "Persian (Iran)"},
			{code: "ff", name: "Fulah"},
			{code: "ff-CM", name: "Fulah (Cameroon)"},
			{code: "ff-GN", name: "Fulah (Guinea)"},
			{code: "ff-MR", name: "Fulah (Mauritania)"},
			{code: "ff-SN", name: "Fulah (Senegal)"},
			{code: "fi", name: "Finnish"},
			{code: "fi-FI", name: "Finnish (Finland)"},
			{code: "fil", name: "Filipino"},
			{code: "fil-PH", name: "Filipino (Philippines)"},
			{code: "fo", name: "Faroese"},
			{code: "fo-DK", name: "Faroese (Denmark)"},
			{code: "fo-FO", name: "Faroese (Faroe Islands)"},
			{code: "fr", name: "French"},
			{code: "fr-BE", name: "French (Belgium)"},
			{code: "fr-BF", name: "French (Burkina Faso)"},
			{code: "fr-BI", name: "French (Burundi)"},
			{code: "fr-BJ", name: "French (Benin)"},
			{code: "fr-BL", name: "French (St. Barthélemy)"},
			{code: "fr-CA", name: "French (Canada)"},
			{code: "fr-CD", name: "French (Congo - Kinshasa)"},
			{code: "fr-CF", name: "French (Central African Republic)"},
			{code: "fr-CG", name: "French (Congo - Brazzaville)"},
			{code: "fr-CH", name: "French (Switzerland)"},
			{code: "fr-CI", name: "French (Côte d’Ivoire)"},
			{code: "fr-CM", name: "French (Cameroon)"},
			{code: "fr-DJ", name: "French (Djibouti)"},
			{code: "fr-DZ", name: "French (Algeria)"},
			{code: "fr-FR", name: "French (France)"},
			{code: "fr-GA", name: "French (Gabon)"},
			{code: "fr-GF", name: "French (French Guiana)"},
			{code: "fr-GN", name: "French (Guinea)"},
			{code: "fr-GP", name: "French (Guadeloupe)"},
			{code: "fr-GQ", name: "French (Equatorial Guinea)"},
			{code: "fr-HT", name: "French (Haiti)"},
			{code: "fr-KM", name: "French (Comoros)"},
			{code: "fr-LU", name: "French (Luxembourg)"},
			{code: "fr-MA", name: "French (Morocco)"},
			{code: "fr-MC", name: "French (Monaco)"},
			{code: "fr-MF", name: "French (St. Martin)"},
			{code: "fr-MG", name: "French (Madagascar)"},
			{code: "fr-ML", name: "French (Mali)"},
			{code: "fr-MQ", name: "French (Martinique)"},
			{code: "fr-MR", name: "French (Mauritania)"},
			{code: "fr-MU", name: "French (Mauritius)"},
			{code: "fr-NC", name: "French (New Caledonia)"},
			{code: "fr-NE", name: "French (Niger)"},
			{code: "fr-PF", name: "French (French Polynesia)"},
			{code: "fr-PM", name: "French (St. Pierre & Miquelon)"},
			{code: "fr-RE", name: "French (Réunion)"},
			{code: "fr-RW", name: "French (Rwanda)"},
			{code: "fr-SC", name: "French (Seychelles)"},
			{code: "fr-SN", name: "French (Senegal)"},
			{code: "fr-SY", name: "French (Syria)"},
			{code: "fr-TD", name: "French (Chad)"},
			{code: "fr-TG", name: "French (Togo)"},
			{code: "fr-TN", name: "French (Tunisia)"},
			{code: "fr-VU", name: "French (Vanuatu)"},
			{code: "fr-WF", name: "French (Wallis & Futuna)"},
			{code: "fr-YT", name: "French (Mayotte)"},
			{code: "fur", name: "Friulian"},
			{code: "fur-IT", name: "Friulian (Italy)"},
			{code: "fy", name: "Western Frisian"},
			{code: "fy-NL", name: "Western Frisian (Netherlands)"},
			{code: "ga", name: "Irish"},
			{code: "ga-IE", name: "Irish (Ireland)"},
			{code: "gd", name: "Scottish Gaelic"},
			{code: "gd-GB", name: "Scottish Gaelic (United Kingdom)"},
			{code: "gl", name: "Galician"},
			{code: "gl-ES", name: "Galician (Spain)"},
			{code: "gsw", name: "Swiss German"},
			{code: "gsw-CH", name: "Swiss German (Switzerland)"},
			{code: "gsw-FR", name: "Swiss German (France)"},
			{code: "gsw-LI", name: "Swiss German (Liechtenstein)"},
			{code: "gu", name: "Gujarati"},
			{code: "gu-IN", name: "Gujarati (India)"},
			{code: "guz", name: "Gusii"},
			{code: "guz-KE", name: "Gusii (Kenya)"},
			{code: "gv", name: "Manx"},
			{code: "gv-IM", name: "Manx (Isle of Man)"},
			{code: "ha", name: "Hausa"},
			{code: "ha-GH", name: "Hausa (Ghana)"},
			{code: "ha-NE", name: "Hausa (Niger)"},
			{code: "ha-NG", name: "Hausa (Nigeria)"},
			{code: "haw", name: "Hawaiian"},
			{code: "haw-US", name: "Hawaiian (United States)"},
			{code: "he", name: "Hebrew"},
			{code: "he-IL", name: "Hebrew (Israel)"},
			{code: "hi", name: "Hindi"},
			{code: "hi-IN", name: "Hindi (India)"},
			{code: "hr", name: "Croatian"},
			{code: "hr-BA", name: "Croatian (Bosnia & Herzegovina)"},
			{code: "hr-HR", name: "Croatian (Croatia)"},
			{code: "hsb", name: "Upper Sorbian"},
			{code: "hsb-DE", name: "Upper Sorbian (Germany)"},
			{code: "hu", name: "Hungarian"},
			{code: "hu-HU", name: "Hungarian (Hungary)"},
			{code: "hy", name: "Armenian"},
			{code: "hy-AM", name: "Armenian (Armenia)"},
			{code: "id", name: "Indonesian"},
			{code: "id-ID", name: "Indonesian (Indonesia)"},
			{code: "ig", name: "Igbo"},
			{code: "ig-NG", name: "Igbo (Nigeria)"},
			{code: "ii", name: "Sichuan Yi"},
			{code: "ii-CN", name: "Sichuan Yi (China)"},
			{code: "is", name: "Icelandic"},
			{code: "is-IS", name: "Icelandic (Iceland)"},
			{code: "it", name: "Italian"},
			{code: "it-CH", name: "Italian (Switzerland)"},
			{code: "it-IT", name: "Italian (Italy)"},
			{code: "it-SM", name: "Italian (San Marino)"},
			{code: "it-VA", name: "Italian (Vatican City)"},
			{code: "ja", name: "Japanese"},
			{code: "ja-JP", name: "Japanese (Japan)"},
			{code: "jgo", name: "Ngomba"},
			{code: "jgo-CM", name: "Ngomba (Cameroon)"},
			{code: "jmc", name: "Machame"},
			{code: "jmc-TZ", name: "Machame (Tanzania)"},
			{code: "ka", name: "Georgian"},
			{code: "ka-GE", name: "Georgian (Georgia)"},
			{code: "kab", name: "Kabyle"},
			{code: "kab-DZ", name: "Kabyle (Algeria)"},
			{code: "kam", name: "Kamba"},
			{code: "kam-KE", name: "Kamba (Kenya)"},
			{code: "kde", name: "Makonde"},
			{code: "kde-TZ", name: "Makonde (Tanzania)"},
			{code: "kea", name: "Kabuverdianu"},
			{code: "kea-CV", name: "Kabuverdianu (Cape Verde)"},
			{code: "khq", name: "Koyra Chiini"},
			{code: "khq-ML", name: "Koyra Chiini (Mali)"},
			{code: "ki", name: "Kikuyu"},
			{code: "ki-KE", name: "Kikuyu (Kenya)"},
			{code: "kk", name: "Kazakh"},
			{code: "kk-KZ", name: "Kazakh (Kazakhstan)"},
			{code: "kkj", name: "Kako"},
			{code: "kkj-CM", name: "Kako (Cameroon)"},
			{code: "kl", name: "Kalaallisut"},
			{code: "kl-GL", name: "Kalaallisut (Greenland)"},
			{code: "kln", name: "Kalenjin"},
			{code: "kln-KE", name: "Kalenjin (Kenya)"},
			{code: "km", name: "Khmer"},
			{code: "km-KH", name: "Khmer (Cambodia)"},
			{code: "kn", name: "Kannada"},
			{code: "kn-IN", name: "Kannada (India)"},
			{code: "ko", name: "Korean"},
			{code: "ko-KP", name: "Korean (North Korea)"},
			{code: "ko-KR", name: "Korean (South Korea)"},
			{code: "kok", name: "Konkani"},
			{code: "kok-IN", name: "Konkani (India)"},
			{code: "ks", name: "Kashmiri"},
			{code: "ks-IN", name: "Kashmiri (India)"},
			{code: "ksb", name: "Shambala"},
			{code: "ksb-TZ", name: "Shambala (Tanzania)"},
			{code: "ksf", name: "Bafia"},
			{code: "ksf-CM", name: "Bafia (Cameroon)"},
			{code: "ksh", name: "Colognian"},
			{code: "ksh-DE", name: "Colognian (Germany)"},
			{code: "kw", name: "Cornish"},
			{code: "kw-GB", name: "Cornish (United Kingdom)"},
			{code: "ky", name: "Kyrgyz"},
			{code: "ky-KG", name: "Kyrgyz (Kyrgyzstan)"},
			{code: "lag", name: "Langi"},
			{code: "lag-TZ", name: "Langi (Tanzania)"},
			{code: "lb", name: "Luxembourgish"},
			{code: "lb-LU", name: "Luxembourgish (Luxembourg)"},
			{code: "lg", name: "Ganda"},
			{code: "lg-UG", name: "Ganda (Uganda)"},
			{code: "lkt", name: "Lakota"},
			{code: "lkt-US", name: "Lakota (United States)"},
			{code: "ln", name: "Lingala"},
			{code: "ln-AO", name: "Lingala (Angola)"},
			{code: "ln-CD", name: "Lingala (Congo - Kinshasa)"},
			{code: "ln-CF", name: "Lingala (Central African Republic)"},
			{code: "ln-CG", name: "Lingala (Congo - Brazzaville)"},
			{code: "lo", name: "Lao"},
			{code: "lo-LA", name: "Lao (Laos)"},
			{code: "lrc", name: "Northern Luri"},
			{code: "lrc-IQ", name: "Northern Luri (Iraq)"},
			{code: "lrc-IR", name: "Northern Luri (Iran)"},
			{code: "lt", name: "Lithuanian"},
			{code: "lt-LT", name: "Lithuanian (Lithuania)"},
			{code: "lu", name: "Luba-Katanga"},
			{code: "lu-CD", name: "Luba-Katanga (Congo - Kinshasa)"},
			{code: "luo", name: "Luo"},
			{code: "luo-KE", name: "Luo (Kenya)"},
			{code: "luy", name: "Luyia"},
			{code: "luy-KE", name: "Luyia (Kenya)"},
			{code: "lv", name: "Latvian"},
			{code: "lv-LV", name: "Latvian (Latvia)"},
			{code: "mas", name: "Masai"},
			{code: "mas-KE", name: "Masai (Kenya)"},
			{code: "mas-TZ", name: "Masai (Tanzania)"},
			{code: "mer", name: "Meru"},
			{code: "mer-KE", name: "Meru (Kenya)"},
			{code: "mfe", name: "Morisyen"},
			{code: "mfe-MU", name: "Morisyen (Mauritius)"},
			{code: "mg", name: "Malagasy"},
			{code: "mg-MG", name: "Malagasy (Madagascar)"},
			{code: "mgh", name: "Makhuwa-Meetto"},
			{code: "mgh-MZ", name: "Makhuwa-Meetto (Mozambique)"},
			{code: "mgo", name: "Metaʼ"},
			{code: "mgo-CM", name: "Metaʼ (Cameroon)"},
			{code: "mk", name: "Macedonian"},
			{code: "mk-MK", name: "Macedonian (Macedonia)"},
			{code: "ml", name: "Malayalam"},
			{code: "ml-IN", name: "Malayalam (India)"},
			{code: "mn", name: "Mongolian"},
			{code: "mn-MN", name: "Mongolian (Mongolia)"},
			{code: "mr", name: "Marathi"},
			{code: "mr-IN", name: "Marathi (India)"},
			{code: "ms", name: "Malay"},
			{code: "ms-BN", name: "Malay (Brunei)"},
			{code: "ms-MY", name: "Malay (Malaysia)"},
			{code: "ms-SG", name: "Malay (Singapore)"},
			{code: "mt", name: "Maltese"},
			{code: "mt-MT", name: "Maltese (Malta)"},
			{code: "mua", name: "Mundang"},
			{code: "mua-CM", name: "Mundang (Cameroon)"},
			{code: "my", name: "Burmese"},
			{code: "my-MM", name: "Burmese (Myanmar [Burma])"},
			{code: "mzn", name: "Mazanderani"},
			{code: "mzn-IR", name: "Mazanderani (Iran)"},
			{code: "naq", name: "Nama"},
			{code: "naq-NA", name: "Nama (Namibia)"},
			{code: "nb", name: "Norwegian Bokmål"},
			{code: "nb-NO", name: "Norwegian Bokmål (Norway)"},
			{code: "nb-SJ", name: "Norwegian Bokmål (Svalbard & Jan Mayen)"},
			{code: "nd", name: "North Ndebele"},
			{code: "nd-ZW", name: "North Ndebele (Zimbabwe)"},
			{code: "nds", name: "Low German"},
			{code: "nds-DE", name: "Low German (Germany)"},
			{code: "nds-NL", name: "Low German (Netherlands)"},
			{code: "ne", name: "Nepali"},
			{code: "ne-IN", name: "Nepali (India)"},
			{code: "ne-NP", name: "Nepali (Nepal)"},
			{code: "nl", name: "Dutch"},
			{code: "nl-AW", name: "Dutch (Aruba)"},
			{code: "nl-BE", name: "Dutch (Belgium)"},
			{code: "nl-BQ", name: "Dutch (Caribbean Netherlands)"},
			{code: "nl-CW", name: "Dutch (Curaçao)"},
			{code: "nl-NL", name: "Dutch (Netherlands)"},
			{code: "nl-SR", name: "Dutch (Suriname)"},
			{code: "nl-SX", name: "Dutch (Sint Maarten)"},
			{code: "nmg", name: "Kwasio"},
			{code: "nmg-CM", name: "Kwasio (Cameroon)"},
			{code: "nn", name: "Norwegian Nynorsk"},
			{code: "nn-NO", name: "Norwegian Nynorsk (Norway)"},
			{code: "nnh", name: "Ngiemboon"},
			{code: "nnh-CM", name: "Ngiemboon (Cameroon)"},
			{code: "nus", name: "Nuer"},
			{code: "nus-SS", name: "Nuer (South Sudan)"},
			{code: "nyn", name: "Nyankole"},
			{code: "nyn-UG", name: "Nyankole (Uganda)"},
			{code: "om", name: "Oromo"},
			{code: "om-ET", name: "Oromo (Ethiopia)"},
			{code: "om-KE", name: "Oromo (Kenya)"},
			{code: "or", name: "Odia"},
			{code: "or-IN", name: "Odia (India)"},
			{code: "os", name: "Ossetic"},
			{code: "os-GE", name: "Ossetic (Georgia)"},
			{code: "os-RU", name: "Ossetic (Russia)"},
			{code: "pa", name: "Punjabi"},
			{code: "pa-Arab", name: "Punjabi (Arabic)"},
			{code: "pa-Arab-PK", name: "Punjabi (Arabic, Pakistan)"},
			{code: "pa-Guru", name: "Punjabi (Gurmukhi)"},
			{code: "pa-Guru-IN", name: "Punjabi (Gurmukhi, India)"},
			{code: "pl", name: "Polish"},
			{code: "pl-PL", name: "Polish (Poland)"},
			{code: "ps", name: "Pashto"},
			{code: "ps-AF", name: "Pashto (Afghanistan)"},
			{code: "pt", name: "Portuguese"},
			{code: "pt-AO", name: "Portuguese (Angola)"},
			{code: "pt-BR", name: "Portuguese (Brazil)"},
			{code: "pt-CH", name: "Portuguese (Switzerland)"},
			{code: "pt-CV", name: "Portuguese (Cape Verde)"},
			{code: "pt-GQ", name: "Portuguese (Equatorial Guinea)"},
			{code: "pt-GW", name: "Portuguese (Guinea-Bissau)"},
			{code: "pt-LU", name: "Portuguese (Luxembourg)"},
			{code: "pt-MO", name: "Portuguese (Macau SAR China)"},
			{code: "pt-MZ", name: "Portuguese (Mozambique)"},
			{code: "pt-PT", name: "Portuguese (Portugal)"},
			{code: "pt-ST", name: "Portuguese (São Tomé & Príncipe)"},
			{code: "pt-TL", name: "Portuguese (Timor-Leste)"},
			{code: "qu", name: "Quechua"},
			{code: "qu-BO", name: "Quechua (Bolivia)"},
			{code: "qu-EC", name: "Quechua (Ecuador)"},
			{code: "qu-PE", name: "Quechua (Peru)"},
			{code: "rm", name: "Romansh"},
			{code: "rm-CH", name: "Romansh (Switzerland)"},
			{code: "rn", name: "Rundi"},
			{code: "rn-BI", name: "Rundi (Burundi)"},
			{code: "ro", name: "Romanian"},
			{code: "ro-MD", name: "Romanian (Moldova)"},
			{code: "ro-RO", name: "Romanian (Romania)"},
			{code: "rof", name: "Rombo"},
			{code: "rof-TZ", name: "Rombo (Tanzania)"},
			{code: "ru", name: "Russian"},
			{code: "ru-BY", name: "Russian (Belarus)"},
			{code: "ru-KG", name: "Russian (Kyrgyzstan)"},
			{code: "ru-KZ", name: "Russian (Kazakhstan)"},
			{code: "ru-MD", name: "Russian (Moldova)"},
			{code: "ru-RU", name: "Russian (Russia)"},
			{code: "ru-UA", name: "Russian (Ukraine)"},
			{code: "rw", name: "Kinyarwanda"},
			{code: "rw-RW", name: "Kinyarwanda (Rwanda)"},
			{code: "rwk", name: "Rwa"},
			{code: "rwk-TZ", name: "Rwa (Tanzania)"},
			{code: "sah", name: "Sakha"},
			{code: "sah-RU", name: "Sakha (Russia)"},
			{code: "saq", name: "Samburu"},
			{code: "saq-KE", name: "Samburu (Kenya)"},
			{code: "sbp", name: "Sangu"},
			{code: "sbp-TZ", name: "Sangu (Tanzania)"},
			{code: "se", name: "Northern Sami"},
			{code: "se-FI", name: "Northern Sami (Finland)"},
			{code: "se-NO", name: "Northern Sami (Norway)"},
			{code: "se-SE", name: "Northern Sami (Sweden)"},
			{code: "seh", name: "Sena"},
			{code: "seh-MZ", name: "Sena (Mozambique)"},
			{code: "ses", name: "Koyraboro Senni"},
			{code: "ses-ML", name: "Koyraboro Senni (Mali)"},
			{code: "sg", name: "Sango"},
			{code: "sg-CF", name: "Sango (Central African Republic)"},
			{code: "shi", name: "Tachelhit"},
			{code: "shi-Latn", name: "Tachelhit (Latin)"},
			{code: "shi-Latn-MA", name: "Tachelhit (Latin, Morocco)"},
			{code: "shi-Tfng", name: "Tachelhit (Tifinagh)"},
			{code: "shi-Tfng-MA", name: "Tachelhit (Tifinagh, Morocco)"},
			{code: "si", name: "Sinhala"},
			{code: "si-LK", name: "Sinhala (Sri Lanka)"},
			{code: "sk", name: "Slovak"},
			{code: "sk-SK", name: "Slovak (Slovakia)"},
			{code: "sl", name: "Slovenian"},
			{code: "sl-SI", name: "Slovenian (Slovenia)"},
			{code: "smn", name: "Inari Sami"},
			{code: "smn-FI", name: "Inari Sami (Finland)"},
			{code: "sn", name: "Shona"},
			{code: "sn-ZW", name: "Shona (Zimbabwe)"},
			{code: "so", name: "Somali"},
			{code: "so-DJ", name: "Somali (Djibouti)"},
			{code: "so-ET", name: "Somali (Ethiopia)"},
			{code: "so-KE", name: "Somali (Kenya)"},
			{code: "so-SO", name: "Somali (Somalia)"},
			{code: "sq", name: "Albanian"},
			{code: "sq-AL", name: "Albanian (Albania)"},
			{code: "sq-MK", name: "Albanian (Macedonia)"},
			{code: "sq-XK", name: "Albanian (Kosovo)"},
			{code: "sr", name: "Serbian"},
			{code: "sr-Cyrl", name: "Serbian (Cyrillic)"},
			{code: "sr-Cyrl-BA", name: "Serbian (Cyrillic, Bosnia & Herzegovina)"},
			{code: "sr-Cyrl-ME", name: "Serbian (Cyrillic, Montenegro)"},
			{code: "sr-Cyrl-RS", name: "Serbian (Cyrillic, Serbia)"},
			{code: "sr-Cyrl-XK", name: "Serbian (Cyrillic, Kosovo)"},
			{code: "sr-Latn", name: "Serbian (Latin)"},
			{code: "sr-Latn-BA", name: "Serbian (Latin, Bosnia & Herzegovina)"},
			{code: "sr-Latn-ME", name: "Serbian (Latin, Montenegro)"},
			{code: "sr-Latn-RS", name: "Serbian (Latin, Serbia)"},
			{code: "sr-Latn-XK", name: "Serbian (Latin, Kosovo)"},
			{code: "sv", name: "Swedish"},
			{code: "sv-AX", name: "Swedish (Åland Islands)"},
			{code: "sv-FI", name: "Swedish (Finland)"},
			{code: "sv-SE", name: "Swedish (Sweden)"},
			{code: "sw", name: "Swahili"},
			{code: "sw-CD", name: "Swahili (Congo - Kinshasa)"},
			{code: "sw-KE", name: "Swahili (Kenya)"},
			{code: "sw-TZ", name: "Swahili (Tanzania)"},
			{code: "sw-UG", name: "Swahili (Uganda)"},
			{code: "ta", name: "Tamil"},
			{code: "ta-IN", name: "Tamil (India)"},
			{code: "ta-LK", name: "Tamil (Sri Lanka)"},
			{code: "ta-MY", name: "Tamil (Malaysia)"},
			{code: "ta-SG", name: "Tamil (Singapore)"},
			{code: "te", name: "Telugu"},
			{code: "te-IN", name: "Telugu (India)"},
			{code: "teo", name: "Teso"},
			{code: "teo-KE", name: "Teso (Kenya)"},
			{code: "teo-UG", name: "Teso (Uganda)"},
			{code: "tg", name: "Tajik"},
			{code: "tg-TJ", name: "Tajik (Tajikistan)"},
			{code: "th", name: "Thai"},
			{code: "th-TH", name: "Thai (Thailand)"},
			{code: "ti", name: "Tigrinya"},
			{code: "ti-ER", name: "Tigrinya (Eritrea)"},
			{code: "ti-ET", name: "Tigrinya (Ethiopia)"},
			{code: "to", name: "Tongan"},
			{code: "to-TO", name: "Tongan (Tonga)"},
			{code: "tr", name: "Turkish"},
			{code: "tr-CY", name: "Turkish (Cyprus)"},
			{code: "tr-TR", name: "Turkish (Turkey)"},
			{code: "tt", name: "Tatar"},
			{code: "tt-RU", name: "Tatar (Russia)"},
			{code: "twq", name: "Tasawaq"},
			{code: "twq-NE", name: "Tasawaq (Niger)"},
			{code: "tzm", name: "Central Atlas Tamazight"},
			{code: "tzm-MA", name: "Central Atlas Tamazight (Morocco)"},
			{code: "ug", name: "Uyghur"},
			{code: "ug-CN", name: "Uyghur (China)"},
			{code: "uk", name: "Ukrainian"},
			{code: "uk-UA", name: "Ukrainian (Ukraine)"},
			{code: "ur", name: "Urdu"},
			{code: "ur-IN", name: "Urdu (India)"},
			{code: "ur-PK", name: "Urdu (Pakistan)"},
			{code: "uz", name: "Uzbek"},
			{code: "uz-Arab", name: "Uzbek (Arabic)"},
			{code: "uz-Arab-AF", name: "Uzbek (Arabic, Afghanistan)"},
			{code: "uz-Cyrl", name: "Uzbek (Cyrillic)"},
			{code: "uz-Cyrl-UZ", name: "Uzbek (Cyrillic, Uzbekistan)"},
			{code: "uz-Latn", name: "Uzbek (Latin)"},
			{code: "uz-Latn-UZ", name: "Uzbek (Latin, Uzbekistan)"},
			{code: "vai", name: "Vai"},
			{code: "vai-Latn", name: "Vai (Latin)"},
			{code: "vai-Latn-LR", name: "Vai (Latin, Liberia)"},
			{code: "vai-Vaii", name: "Vai (Vai)"},
			{code: "vai-Vaii-LR", name: "Vai (Vai, Liberia)"},
			{code: "vi", name: "Vietnamese"},
			{code: "vi-VN", name: "Vietnamese (Vietnam)"},
			{code: "vun", name: "Vunjo"},
			{code: "vun-TZ", name: "Vunjo (Tanzania)"},
			{code: "wae", name: "Walser"},
			{code: "wae-CH", name: "Walser (Switzerland)"},
			{code: "wo", name: "Wolof"},
			{code: "wo-SN", name: "Wolof (Senegal)"},
			{code: "xog", name: "Soga"},
			{code: "xog-UG", name: "Soga (Uganda)"},
			{code: "yav", name: "Yangben"},
			{code: "yav-CM", name: "Yangben (Cameroon)"},
			{code: "yi", name: "Yiddish"},
			{code: "yi-001", name: "Yiddish (World)"},
			{code: "yo", name: "Yoruba"},
			{code: "yo-BJ", name: "Yoruba (Benin)"},
			{code: "yo-NG", name: "Yoruba (Nigeria)"},
			{code: "yue", name: "Cantonese"},
			{code: "yue-Hans", name: "Cantonese (Simplified)"},
			{code: "yue-Hans-CN", name: "Cantonese (Simplified, China)"},
			{code: "yue-Hant", name: "Cantonese (Traditional)"},
			{
				code: "yue-Hant-HK",
				name: "Cantonese (Traditional, Hong Kong SAR China)"
			},
			{code: "zgh", name: "Standard Moroccan Tamazight"},
			{code: "zgh-MA", name: "Standard Moroccan Tamazight (Morocco)"},
			{code: "zh", name: "Chinese"},
			{code: "zh-Hans", name: "Chinese (Simplified)"},
			{code: "zh-Hans-CN", name: "Chinese (Simplified, China)"},
			{code: "zh-Hans-HK", name: "Chinese (Simplified, Hong Kong SAR China)"},
			{code: "zh-Hans-MO", name: "Chinese (Simplified, Macau SAR China)"},
			{code: "zh-Hans-SG", name: "Chinese (Simplified, Singapore)"},
			{code: "zh-Hant", name: "Chinese (Traditional)"},
			{
				code: "zh-Hant-HK",
				name: "Chinese (Traditional, Hong Kong SAR China)"
			},
			{code: "zh-Hant-MO", name: "Chinese (Traditional, Macau SAR China)"},
			{code: "zh-Hant-TW", name: "Chinese (Traditional, Taiwan)"},
			{code: "zu", name: "Zulu"},
			{code: "zu-ZA", name: "Zulu (South Africa)"}
		]
	}
]
